# Introduction to Neural Networks

We will definitely need to deal with arrays and other numerical functions, so import numpy.

In [1]:
import numpy as np

Here's how to call the exponential function.

In [2]:
np.exp(1)

2.7182818284590451

For us, np.arrays will be better than ordinary python lists.  There are numerous reasons for this.  Here are a few things to be aware of regarding lists and np.arrays presented by examples.

In [3]:
mylist=[1,2,3]
mynplist=np.array([1,2,3])

In [4]:
print np.exp(mylist)

[  2.71828183   7.3890561   20.08553692]


In [5]:
# can't add an integer and a list
# print 1+mylist

In [5]:
# you can add an integer and an np.array
print 1+mynplist

[2 3 4]


In [7]:
# can't divide an integer by a list
# 2/mylist

In [6]:
# you can divide an integer by an np.array.  Be aware that if the np.array is filled with integers, then you'll get integer division
print 2/mynplist

[2 1 0]


In [7]:
# you can divide a float by an np.array.  Here, the integers in the np.array are converted to floats and division is division of floating point numbers
print 2.0/mynplist

[ 2.          1.          0.66666667]


## The sigmoid function

We now define a function $\sigma:\mathbb{R}\to \mathbb{R}$ by

$$\sigma(x)=\frac{1}{1+\exp(-x)}$$

I'm denoting this function by the greek letter sigma, but this function is called <em>sigmoid</em> function.

In [8]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [9]:
# sigmoid of negative numbers are close to zero
sigmoid(np.array([-10,-20,-30,-40]))

array([  4.53978687e-05,   2.06115362e-09,   9.35762297e-14,
         4.24835426e-18])

In [10]:
# sigmoid of positive numbers are close to one
sigmoid(np.array([10,20,30,40]))

array([ 0.9999546,  1.       ,  1.       ,  1.       ])

Lets plot the sigmoid function

In [11]:
import matplotlib
import matplotlib.pyplot as plt

In [12]:
xvals = np.linspace(-20,20,1001)
yvals = sigmoid(xvals)
fig = plt.figure()
axes = fig.add_axes([0.1, 0.1, 0.9, 0.8])
axes.plot(xvals,yvals)

Think of the sigmoid function as capturing the idea of a neuron activating.  A number $x$ can be thought of a signal strength entering a neuron and the value $\sigma(x)\in (0,1)$ gives the probability that the neuron fires.

## Neural Networks: compositions of sigmoid functions

Now, we will consider certain compositions of sigmoid functions.  It will be convenient to have a visual language for these compositions, rather than writing formulas.  The visual language will be a directed graph with nodes and edges.   The nodes represent the sigmoid function, the edges are labelled by real numbers called <em>weights</em>, and open initial edges represent an input for a real number.  Multiple edges coming into a node are summed before applying the sigmoid function.  Here's a picture:

<img src="./nn2.png" />

A more complicated picture like this

<img src="./nn1.png" />

represents either
<ul>
    <li>a single function $\mathbb{R}^3 \to \mathbb{R}$, if the edges are labelled by weights</li>
    <li>a set of functions $\mathbb{R}^3 \to \mathbb{R}$, if the edges are unlabelled</li>
</ul>


Let's look more closely at the simple picture above with one node and three input edges.  We'll fix some weights $\theta_0=-400$, $\theta_1=20$, and $\theta_2=50$.  We'll assume that $x_0=1$ and we'll look at a bunch of random points $x_1, x_2$ in the rectangle $[0,10]\times [0,10]$.  If the neuron fires for those values, we'll plot the point red and if the neuron doesn't fire, we'll plot the point blue.  Let's set the firing threshold to be $0.9$.

In [13]:
randomxpoints=10*np.random.rand(800)
randomypoints=10*np.random.rand(800)

In [14]:
thetavec=np.array([-8,-1,2])
rpts=[] ; bpts=[]
for i in range(800):
    xvec=np.array([1,randomxpoints[i],randomypoints[i]])
    xdottheta=np.dot(thetavec,xvec)
    if(sigmoid(xdottheta)>.9):
        rpts.append([randomxpoints[i],randomypoints[i]])
    else:
        bpts.append([randomxpoints[i],randomypoints[i]])
redpoints=np.array(rpts)
bluepoints=np.array(bpts)

In [15]:
from __future__ import print_function

In [16]:
xvalsR = redpoints[:,0] #prints first column
yvalsR = redpoints[:,1] #prints second column
xvalsB = bluepoints[:,0] #prints 
yvalsB = bluepoints[:,1]
fig = plt.figure()
axes = fig.add_axes([0.1, 0.1, 0.9, 0.8])
axes.plot(xvalsR,yvalsR,'r+',xvalsB,yvalsB,'b.')

### Exercise
Explain how the network above classifies points as red if they lie above a certain line or blue if they lie below that line.

Here's a picture of a more sophisticated network and a picture of how it classifies some random points.

<img src="./nn3.png" />


In [17]:
thetavec1=np.array([-300,20,50])
thetavec2=np.array([80,-20,10])
thetavec3=np.array([-30,10,20])
rpts=[] ; bpts=[]
for i in range(800):
    xvec=np.array([1,randomxpoints[i],randomypoints[i]])
    a0=sigmoid(np.dot(thetavec1,xvec))
    a1=sigmoid(np.dot(thetavec2,xvec))
    a=np.array([1,a0,a1])
    out=sigmoid(np.dot(thetavec3,a))
    if(out>.9):
        rpts.append([randomxpoints[i],randomypoints[i]])
    else:
        bpts.append([randomxpoints[i],randomypoints[i]])
redpoints=np.array(rpts)
bluepoints=np.array(bpts)

In [22]:
xvalsR = redpoints[:,0]
yvalsR = redpoints[:,1]
xvalsB = bluepoints[:,0]
yvalsB = bluepoints[:,1]
t=np.arange(0.,10.,0.1)
fig = plt.figure()
axes = fig.add_axes([0.1, 0.1, 0.9, 0.8])
axes.plot(xvalsR,yvalsR,'r+',xvalsB,yvalsB,'b.', t,1.6095-t,'g.',t,2*t-7.781,'y.',t,-0.4*t+6.0439,'k')

IndexError: too many indices for array

### Exercise
Explain how the network above classifies points as red or blue.