# My solution to Problem 2, assignment 3

In [9]:
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

In [10]:
%matplotlib inline

## Step 1. Write a gradient descent algorithm

In [83]:
def my_grad_desc(g,dg,x,tol_1,tol_2,max_steps):
    counter =0
    for i in range(max_steps):
        #print i,x,g(x)
        g0 = g(x)
        grad = dg(x)
        norm_grad = np.linalg.norm(grad)
        counter +=1
        if counter % 20 == 0:
            print norm_grad
        if norm_grad < tol_1:
            #print "gradient norm less than ", tol_1
            #print "min value of ", g0," obtained in ",i+1," steps."
            return x
            break
        unit_grad = (1/norm_grad)*grad
        alpha0=0; alpha2=1
        g2 = g(x-alpha2*unit_grad)
        while g2 >= g0:
            alpha2 = 0.5*alpha2
            g2 = g(x-alpha2*unit_grad)
            if alpha2 < tol_1:
                #print "step size less than ", tol_1
                #print "min value of ", g0," obtained in ",i+1," steps."
                return x
                break
        alpha1 = 0.5*alpha2
        g1 = g(x-alpha1*unit_grad)
        h0 = (g1-g0)/alpha1
        h1 = (g2-g1)/(alpha2-alpha1)
        h2 = (h1-h0)/alpha2
        alpha0=0.5*(alpha1-h0/h2)
        g00=g(x-alpha0*unit_grad)
        if abs(g00-g0) < tol_2 :
            #print "functional values less than ", tol_2
            return x
            break
        x = x-alpha0*unit_grad
    #print("iteration limit reached.  min value of ", g0," obtained in ",i+1," steps.")
    return x

Let's test the gradient descent program

In [12]:
def testf(x):
    return (x-1)**2*(x**2+10+np.cos(x))

In [36]:
def myf(x):
    return (x**2)-1

In [13]:
def testdf(x):
    return 2*(x-1)*(x**2+10+np.cos(x))+(x-1)**2*(2*x-np.sin(x))

In [37]:
def mydf(x):
    return 2*x

In [38]:
print myf(4)
mydf(4)

15


8

In [39]:
testdf(10)

3628.9624224586632

In [40]:
(testf(10.000001)-testf(10))/.000001

3628.963013397879

In [41]:
my_grad_desc(testf,testdf,10,10**(-8),10**(-8),100)

0.9999999957195147

In [46]:
my_grad_desc(myf,mydf,1,10**(-8),10**(-8),100)

2.0
0.0


0.0

### Exercise:  add a Boolean input specifying whether the gradient descent program should provide verbose output or not

## Step 2. Define the function $\mu$, the cost function, and the gradient of the cost function

In [48]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [49]:
def dsigmoid(x):
    s=sigmoid(x)
    return s*(1-s)

Let's test whether our derivative is correct

In [50]:
print (sigmoid(1.000001)-sigmoid(1))/.000001
print dsigmoid(1)

0.196611887771
0.196611933241


In [51]:
for i in range(0,12,3):
    print i

0
3
6
9


In [57]:
def mu(theta,x):
    # assuming theta = [t0, t1, ..., t11]
    musum=0
    for i in range(0,12,3):
        musum+=theta[i]*sigmoid(theta[i+1]+theta[i+2]*x)
    return musum

In [58]:
mu([0,1,2,3,4,5,6,7,8,9,10,11],5)

17.999999999999236

In [59]:
data=np.linspace(0,2*np.pi,100)
y=np.sin(data)

In [60]:
data

array([ 0.        ,  0.06346652,  0.12693304,  0.19039955,  0.25386607,
        0.31733259,  0.38079911,  0.44426563,  0.50773215,  0.57119866,
        0.63466518,  0.6981317 ,  0.76159822,  0.82506474,  0.88853126,
        0.95199777,  1.01546429,  1.07893081,  1.14239733,  1.20586385,
        1.26933037,  1.33279688,  1.3962634 ,  1.45972992,  1.52319644,
        1.58666296,  1.65012947,  1.71359599,  1.77706251,  1.84052903,
        1.90399555,  1.96746207,  2.03092858,  2.0943951 ,  2.15786162,
        2.22132814,  2.28479466,  2.34826118,  2.41172769,  2.47519421,
        2.53866073,  2.60212725,  2.66559377,  2.72906028,  2.7925268 ,
        2.85599332,  2.91945984,  2.98292636,  3.04639288,  3.10985939,
        3.17332591,  3.23679243,  3.30025895,  3.36372547,  3.42719199,
        3.4906585 ,  3.55412502,  3.61759154,  3.68105806,  3.74452458,
        3.8079911 ,  3.87145761,  3.93492413,  3.99839065,  4.06185717,
        4.12532369,  4.1887902 ,  4.25225672,  4.31572324,  4.37

In [61]:
y

array([  0.00000000e+00,   6.34239197e-02,   1.26592454e-01,
         1.89251244e-01,   2.51147987e-01,   3.12033446e-01,
         3.71662456e-01,   4.29794912e-01,   4.86196736e-01,
         5.40640817e-01,   5.92907929e-01,   6.42787610e-01,
         6.90079011e-01,   7.34591709e-01,   7.76146464e-01,
         8.14575952e-01,   8.49725430e-01,   8.81453363e-01,
         9.09631995e-01,   9.34147860e-01,   9.54902241e-01,
         9.71811568e-01,   9.84807753e-01,   9.93838464e-01,
         9.98867339e-01,   9.99874128e-01,   9.96854776e-01,
         9.89821442e-01,   9.78802446e-01,   9.63842159e-01,
         9.45000819e-01,   9.22354294e-01,   8.95993774e-01,
         8.66025404e-01,   8.32569855e-01,   7.95761841e-01,
         7.55749574e-01,   7.12694171e-01,   6.66769001e-01,
         6.18158986e-01,   5.67059864e-01,   5.13677392e-01,
         4.58226522e-01,   4.00930535e-01,   3.42020143e-01,
         2.81732557e-01,   2.20310533e-01,   1.58001396e-01,
         9.50560433e-02,

In [62]:
def cost(theta):
    totalcost=0
    for i in range(100):
        totalcost+=(mu(theta,data[i])-y[i])**2
    return (1.0/200)*totalcost

In [63]:
def gradcost(theta):
    gradvect=np.zeros(12)
    for x in data:
        dcostdmu=(mu(theta,x)-np.sin(x))
        for i in range(0,12,3):
            term=dcostdmu*theta[i]*dsigmoid(theta[i+1]+theta[i+2]*x)
            gradvect[i]+=dcostdmu*sigmoid(theta[i+1]+theta[i+2]*x)
            gradvect[i+1]+=term
            gradvect[i+2]+=term*x
    return 1.0/100*gradvect

In [71]:
mytheta0=np.random.rand(12)

In [72]:
cost(mytheta0)

0.69899416764800226

In [73]:
gradcost(mytheta0)

array([ 0.54013941,  0.02236873,  0.09934042,  0.75090432,  0.03190471,
        0.13289428,  0.8633875 ,  0.01261109,  0.03218923,  0.8663356 ,
        0.00135442,  0.00323936])

Let's test whether our derivative is correct

In [74]:
numgrad=np.zeros(12)
for i in range(12):
    zerovect=np.zeros(12)
    zerovect[i]=1
    numgrad[i]=10**5*(cost(mytheta0+10**(-5)*zerovect)-cost(mytheta0))

In [75]:
print numgrad-gradcost(mytheta0)

[  1.71267755e-06  -2.06175643e-08  -5.05459709e-07   3.07104989e-06
  -9.41282495e-08  -2.12428529e-06   4.10777674e-06  -1.95120175e-08
  -6.01527909e-07   4.18114151e-06  -4.19461584e-09  -6.30807671e-08]


## Step 3.  Search for parameters that minimize cost

In [86]:
sol_theta=my_grad_desc(cost,gradcost,mytheta0,10**(-10),10**(-10),100)

0.0782246949958


0.0278997399883


0.0161349577611


0.0163601911649


0.0176385882904


In [87]:
cost(sol_theta)

0.076405069968748116

In [89]:
fig = plt.figure()
axes = fig.add_axes([0.1, 0.1, 0.9, 0.7]) 
axes.plot(data,np.sin(data),c="r");
axes.plot(data,mu(sol_theta,data),c="b");

Not bad, but let's run some trials to see if we can do better

In [93]:
best_theta=np.zeros(12)
best_initial_theta=np.zeros(12)
num_trials=10
for i in range(num_trials):
    print "trial ",i
    random_theta=2*np.random.rand(12)
    sol_theta=my_grad_desc(cost,gradcost,random_theta,10**(-10),10**(-10),300)
    if cost(sol_theta)<cost(best_theta):
        print "improved parameters with cost ",cost(sol_theta)," found"
        best_theta=sol_theta
        best_initial_theta=random_theta
print "Trials complete"

trial  0


0.138949004909


0.051811777057


0.0388430490717


0.0370475342069


0.0375846612345


0.0387096715688


0.0397978622429


0.0403716324042


0.0400258121301


0.0385533129059


0.0360516843434


0.0328582250605


0.0293741399108


0.0259362482224


0.0228626822252
improved parameters with cost  0.0351140111966  found
trial  1


0.132935967582


0.043497009874


0.0261723548982


0.0234846720563


0.0237407222293


0.0248899910197


0.0264973176654


0.0285305950047


0.0308566931107


0.032383381733


0.0326600381539


0.0328431859502


0.0328498101214


0.0326008360036


0.0320366891929
trial  2


0.0570170154603


0.0391491118122


0.0404600712939


0.0431719068015


0.0450449191237


0.0461675503159


0.0465574974829


0.0460138362714


0.043564850891


0.0399001533102


0.0357937391412


0.0318328390918


0.0283948298445


0.0260285645666


0.0238442371222
improved parameters with cost  0.0210044611419  found
trial  3


0.0686335689452


0.106886475427


0.0944209176773


0.0355518724375


0.0333875718156


0.0319161504734


0.0305960737362


0.0292551505558


0.0277915222577


0.0261637893855


0.0243909779921


0.0226359471659


0.0210266348836


0.0196185083224


0.0183822425453
improved parameters with cost  0.0135780306138  found
trial  4


0.0481161699234


0.0639588648256


0.0832771706883


0.0913888412986


0.0751395471917


0.0512255107604


0.0336628255455


0.0246889404823


0.0208874136542


0.0196387014624


0.0194063134306


0.01954278317


0.0198122493365


0.0201214678146


0.0204166538807
trial  5


0.00825068594354


0.00947930040344


0.0111512569546


0.0134442471323


0.0167160421483


0.0217161773524


0.0301881811356


0.0477694651985


0.0923167922631


0.0466094867668


0.0127918127704


0.0133240312395


0.0165363308145


0.0182105972267


0.0141691456099
trial  6


0.151674349602


0.11478878591


0.0841713230017


0.0531448033037


0.0340234956203


0.0251968593294


0.0219159610001


0.0211017070435


0.0211159880278


0.0213721204216


0.0216871906625


0.0219953946547


0.0222579650283


0.0224396072444


0.022504756853
trial  7


0.033390257927


0.0227181228003


0.0208558703993


0.0206201733755


0.0203936125138


0.0205494908595


0.0209942080045


0.0216778877014


0.0225707066535


0.0236516341923


0.0249010676398


0.0259720840608


0.0265525912601


0.0270148549144


0.0272915606918
trial  8


0.0998082389603


0.0556466055709


0.035116013568


0.0268510238213


0.0255159867747


0.0257567842815


0.0264774183863


0.0273961816003


0.0283918839053


0.0293164147794


0.0295939602736


0.0296463390002


0.0294699549107


0.0292789895836


0.0288537550451
trial  9


0.0580019667437


0.0727395312185


0.0715881807497


0.0476906370779


0.0263422681069


0.0183829770373


0.0172222662522


0.0177698269032


0.0184915758096


0.0189444708427


0.0189348007462


0.0184117929836


0.0174377371776


0.0161296088193


0.0146177882391
Trials complete


In [91]:
best_theta

array([ 1.4601537 , -0.22055686,  1.98363458,  3.31852192,  4.89580908,
       -1.62501499, -2.11213042,  1.88755446, -0.34731965, -2.50011727,
        1.39052284, -0.28882046])

In [94]:
best_theta

array([ 1.82992185, -1.2636912 ,  2.33014093,  3.05662498,  4.17035386,
       -1.51112569, -2.42562383,  1.31052716, -0.32273614, -1.62580399,
        1.96637536,  1.57767638])

In [95]:
fig = plt.figure()
axes = fig.add_axes([0.1, 0.1, 0.9, 0.7]) 
axes.plot(data,np.sin(data),c="r");
axes.plot(data,mu(best_theta,data),c="b");

### Exercise:  Program a solution using stochastic gradient.  Try mini-batches of size 20.

.022 -> .007